apiVersion: v1
kind: Deployment 
metadata: 
  name: imageclassificationapp 
spec: 
  selector: 
    matchLabels: 
      app: imageclassificationapp 
  replicas: 5 # tells deployment to run 2 pods matching the template 
  template:
    metadata: 
      labels: 
        app: imageclassificationapp 
    spec: 
      containers: 
      - name: model-api 
        image: crrq51278013.azurecr.io/model-api:165
        ports: 
        - containerPort: 88

kind: Service 
apiVersion: v1 
metadata: 
  name: imageclassificationapp
spec: 
  selector: 
    app: imageclassificationapp 
  ports: 
  - protocol: TCP 
    port: 80 
    targetPort: 80 
  type: LoadBalancer 

