apiVersion: v1
kind: Pod
metadata:
 name: imageclassificationapp
spec:
 containers:
   - name: model-api
     image: crrq51278013.azurecr.io/model-api:196
     ports:
       - containerPort: 88
 imagePullSecrets:
   - name: imageclassificationapp
