apiVersion: v1
kind: Deployment 
metadata: 
  name: imageclassificationapp 
spec: 
  selector: 
    matchLabels: 
      app: imageclassificationapp 
  replicas: 2 # tells deployment to run 2 pods matching the template 
  template:
    metadata: 
      labels: 
        app: imageclassificationapp 
    spec: 
      containers: 
      - name: model-api 
        image: crrq51278013.azurecr.io/model-api:178
        ports: 
        - containerPort: 88

kind: Service 
apiVersion: v1 
metadata: 
  name: imageclassificationapp
spec: 
  selector: 
    app: imageclassificationapp 
  ports: 
  - protocol: TCP 
    port: 88 
    targetPort: 88 
  type: LoadBalancer 
   
kind: Ingress
apiVersion: extensions/v1 
metadata:
 name: imageclassificationapp
 annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
        serviceName: imageclassificationapp
        servicePort: 88
