apiVersion: apps/v1
kind: Pod 
metadata:
 name: imageclassificationapp
spec:
 containers:
   - name: model-api
     image: crrq51278013.azurecr.io/model-api:175
     ports:
       - containerPort: 88
 imagePullSecrets:
   - name: imageclassificationappdemosecret
   
kind: Ingress
apiVersion: v1 
metadata:
 name: imageclassificationapp
 annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
        serviceName: imageclassificationapp-service
        servicePort: 88
